export const users = [
  {
    name: "First TestUser",
    username: "firsttestuser",
    email: "firsttestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2002-10-08",
    role: "user",
  },
  {
    name: "Second TestUser",
    username: "secondtestuser",
    email: "secondtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1999-03-14",
    role: "user",
  },
  {
    name: "Third TestUser",
    username: "thirdtestuser",
    email: "thirdtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2001-07-21",
    role: "user",
  },
  {
    name: "Fourth TestUser",
    username: "fourthtestuser",
    email: "fourthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1998-11-02",
    role: "user",
  },
  {
    name: "Fifth TestUser",
    username: "fifthtestuser",
    email: "fifthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2000-01-30",
    role: "user",
  },
  {
    name: "Sixth TestUser",
    username: "sixthtestuser",
    email: "sixthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1997-05-18",
    role: "user",
  },
  {
    name: "Seventh TestUser",
    username: "seventhtestuser",
    email: "seventhtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2003-09-09",
    role: "user",
  },
  {
    name: "Eighth TestUser",
    username: "eighthtestuser",
    email: "eighthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1996-12-25",
    role: "user",
  },
  {
    name: "Ninth TestUser",
    username: "ninthtestuser",
    email: "ninthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2001-04-11",
    role: "user",
  },
  {
    name: "Tenth TestUser",
    username: "tenthtestuser",
    email: "tenthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1995-08-19",
    role: "user",
  },
  {
    name: "Eleventh TestUser",
    username: "eleventhtestuser",
    email: "eleventhtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2002-02-16",
    role: "user",
  },
  {
    name: "Twelfth TestUser",
    username: "twelfthtestuser",
    email: "twelfthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1999-10-07",
    role: "user",
  },
  {
    name: "Thirteenth TestUser",
    username: "thirteenthtestuser",
    email: "thirteenthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2000-06-03",
    role: "user",
  },
  {
    name: "Fourteenth TestUser",
    username: "fourteenthtestuser",
    email: "fourteenthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1998-09-27",
    role: "user",
  },
  {
    name: "Fifteenth TestUser",
    username: "fifteenthtestuser",
    email: "fifteenthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2001-12-12",
    role: "user",
  },
  {
    name: "Sixteenth TestUser",
    username: "sixteenthtestuser",
    email: "sixteenthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1997-03-29",
    role: "user",
  },
  {
    name: "Seventeenth TestUser",
    username: "seventeenthtestuser",
    email: "seventeenthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2003-05-05",
    role: "user",
  },
  {
    name: "Eighteenth TestUser",
    username: "eighteenthtestuser",
    email: "eighteenthtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1996-07-22",
    role: "user",
  },
  {
    name: "Nineteenth TestUser",
    username: "nineteenthtestuser",
    email: "nineteenthtestuser@gmail.com",
    password: "password",
    gender: "M",
    dateOfBirth: "2000-11-15",
    role: "user",
  },
  {
    name: "Twentieth TestUser",
    username: "twentiethtestuser",
    email: "twentiethtestuser@gmail.com",
    password: "password",
    gender: "F",
    dateOfBirth: "1999-01-08",
    role: "user",
  },
];