import express from "express";
import { destroy, index, show, store, update, getMe } from "../controllers/userController";
import { authenticateUser } from "../middleware/auth";
import { login } from "../controllers/login";
import { like, matches, readLikes, unreadLikes, userLikes } from "../controllers/actionsController";
import { allNotifications, newLikes } from "../controllers/notificationsController";
import { updatePassword } from "../controllers/passwordController";
import { blockUser, destroyBlock, restrictBlocked } from "../controllers/blockUserController";
import { report, reports } from "../controllers/reportUserController";
import { filterUsers } from "../controllers/filterController";
import { bannedUsers, banUser, unbanUser } from "../controllers/admin/banUsersController";

const userRouter = express.Router();
userRouter.post("/signup", store);
userRouter.post("/login", login);
userRouter.post("/block-user", authenticateUser, blockUser);
userRouter.get("/", index);
userRouter.get("/banned", authenticateUser, bannedUsers);
userRouter.get("/me", authenticateUser, getMe);
userRouter.get("/new-likes", authenticateUser, newLikes);
userRouter.get("/user-likes", authenticateUser, userLikes);
userRouter.get("/unread-likes", authenticateUser, unreadLikes);
userRouter.get("/all-new-notifications", authenticateUser, allNotifications);
userRouter.patch("/profile/update", authenticateUser, update);
userRouter.patch("/read-likes", authenticateUser, readLikes);
userRouter.get("/my-matches", authenticateUser, matches);
userRouter.patch("/user/update-password", updatePassword);
userRouter.get("/blocked", authenticateUser, restrictBlocked);
userRouter.delete("/unblock-user/:user", authenticateUser, destroyBlock);
userRouter.get("/reports", authenticateUser, reports);
userRouter.get("/searched", filterUsers);
userRouter.post("/report-user/:user", authenticateUser, report);
userRouter.post("/:to/likes", authenticateUser, like);
userRouter.get("/:user", show);
userRouter.patch("/ban-user/:user", authenticateUser, banUser);
userRouter.patch("/remove-ban/:user", authenticateUser, unbanUser);

userRouter.delete("/:user", authenticateUser, destroy);
export default userRouter;
