import express from "express";
import { destroy, index, show, store, update, getMe } from "../controllers/userController";
import { authenticateUser } from "../middleware/auth";
import { login } from "../controllers/login";
import { like, matches, readLikes, unreadLikes, userLikes } from "../controllers/actionsController";
import { allNotifications, newLikes } from "../controllers/notificationsController";
import { updatePassword } from "../controllers/passwordController";

const userRouter = express.Router();
userRouter.post("/signup", store);
userRouter.post("/login", login);
userRouter.get("/", index);
userRouter.get("/me", authenticateUser, getMe);
userRouter.get("/new-likes", authenticateUser, newLikes);
userRouter.get("/user-likes", authenticateUser, userLikes);
userRouter.get("/unread-likes", authenticateUser, unreadLikes);
userRouter.get("/all-new-notifications", authenticateUser, allNotifications);
userRouter.patch("/profile/update", authenticateUser, update);
userRouter.patch("/read-likes", authenticateUser, readLikes);
userRouter.get("/my-matches", authenticateUser, matches);
userRouter.patch("/user/update-password", updatePassword);
userRouter.post("/:to/likes", authenticateUser, like);
userRouter.get("/:user", show);
userRouter.delete("/:user", authenticateUser, destroy);
export default userRouter;
